<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        Product::truncate();

        $products = [
            [
                'name'         => 'Dynamyst',
                'type'         => 'Signature',
                'gender'       => 'Pria',
                'variant'      => 'Citrus, Fresh Accord',
                'top_notes'    => 'Citrus, Fresh Accord',
                'middle_notes' => 'Aquatic, Green Notes',
                'base_notes'   => 'Musk, Amber, Woody',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '30ml',
                'price'        => 45000,
                'stock'        => 100,
                'best_seller'  => true,
                'image'        => 'assets/images/dynamist.png',
                'description'  => 'Aroma fresh, sporty, dan clean dengan sentuhan hangat yang memberikan kesan maskulin, energik, dan percaya diri. Cocok digunakan untuk aktivitas sehari-hari.',
                'tagline'      => 'Fresh, sporty, clean',
            ],
            [
                'name'         => 'Vanessence',
                'type'         => 'Signature',
                'gender'       => 'Wanita',
                'variant'      => 'Vanilla, Fresh Notes',
                'top_notes'    => 'Vanilla, Fresh Notes',
                'middle_notes' => 'Green Tea, Soft Floral',
                'base_notes'   => 'Creamy Vanilla, Musk',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '30ml',
                'price'        => 45000,
                'stock'        => 100,
                'best_seller'  => true,
                'image'        => 'assets/images/penisence.webp',
                'description'  => 'Aroma vanilla yang lembut, creamy, dan elegan dengan nuansa hangat yang menenangkan. Cocok untuk penggunaan sehari-hari maupun momen spesial.',
                'tagline'      => 'Lembut, creamy, elegan',
            ],
            [
                'name'         => 'VS Scandalous (Refill)',
                'type'         => 'Refill',
                'gender'       => 'Unisex',
                'variant'      => 'Raspberry, Pear',
                'top_notes'    => 'Raspberry, Pear',
                'middle_notes' => 'Peony',
                'base_notes'   => 'Praline, Black Musk',
                'packaging'    => 'Refill Pouch',
                'size'         => '15, 35, 50',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma fruity yang manis dan playful dengan sentuhan floral lembut. Memberikan kesan feminin, ceria, dan menggoda, cocok untuk aktivitas santai maupun hangout.',
                'tagline'      => 'Manis, playful, floral',
            ],
            [
                'name'         => 'VS Romantic Wish',
                'type'         => 'Refill',
                'gender'       => 'Unisex',
                'variant'      => 'Mandarin, Red Fruits',
                'top_notes'    => 'Mandarin, Red Fruits',
                'middle_notes' => 'Freesia, Jasmine',
                'base_notes'   => 'Musk, Sandalwood',
                'packaging'    => 'Refill Pouch',
                'size'         => '15, 35, 51',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Perpaduan buah segar dan bunga yang lembut menghasilkan aroma romantis, manis, dan elegan. Cocok untuk penggunaan sehari-hari.',
                'tagline'      => 'Romantis, manis, elegan',
            ],
            [
                'name'         => 'Dior Sauvage',
                'type'         => 'Refill',
                'gender'       => 'Unisex',
                'variant'      => 'Bergamot, Pepper',
                'top_notes'    => 'Bergamot, Pepper',
                'middle_notes' => 'Lavender, Geranium, Sichuan Pepper',
                'base_notes'   => 'Ambroxan, Cedarwood, Labdanum',
                'packaging'    => 'Refill Pouch',
                'size'         => '15, 35, 52',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma fresh spicy dengan karakter maskulin yang kuat. Membawa kesan bersih, berani, modern, dan penuh percaya diri untuk segala suasana.',
                'tagline'      => 'Fresh spicy, maskulin',
            ],
            [
                'name'         => 'Aigner Black',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Pria',
                'variant'      => 'Bergamot, Grapefruit, Orange',
                'top_notes'    => 'Bergamot, Grapefruit, Orange',
                'middle_notes' => 'Mint, Oakmoss, Pine Tree',
                'base_notes'   => 'Leather, Tonka Bean, Musk',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '15, 35, 53',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma maskulin dengan sentuhan leather, woody, dan warm spicy yang elegan.',
                'tagline'      => 'Leather, woody, warm spicy',
            ],
            [
                'name'         => 'Aigner Blue Emotion',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Pria',
                'variant'      => 'Bergamot, Mandarin, Lemon',
                'top_notes'    => 'Bergamot, Mandarin, Lemon',
                'middle_notes' => 'Coriander, Cardamom, Jasmine',
                'base_notes'   => 'Teak Wood, Ebony, Musk',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '15, 35, 54',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma fresh spicy dan citrus yang maskulin dengan sentuhan kayu dan musk.',
                'tagline'      => 'Fresh spicy, citrus, aromatic',
            ],
            [
                'name'         => 'Aqua Kiss (VS)',
                'type'         => 'Body Mist',
                'gender'       => 'Wanita',
                'variant'      => 'Freesia, Aloe Vera',
                'top_notes'    => 'Freesia, Aloe Vera',
                'middle_notes' => 'Daisy, Sea Notes, Sweet Notes',
                'base_notes'   => 'Chamomile, Plum Blossom',
                'packaging'    => 'Botol Spray',
                'size'         => '15, 35, 55',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Segar dan marine, cocok untuk gaya santai dengan kesan ringan dan feminin.',
                'tagline'      => 'Segar, floral, aquatic',
            ],
            [
                'name'         => 'Baccarat Rouge 540',
                'type'         => 'Eau de Parfum',
                'gender'       => 'Unisex',
                'variant'      => 'Saffron, Jasmine',
                'top_notes'    => 'Saffron, Jasmine',
                'middle_notes' => 'Amberwood, Ambergris',
                'base_notes'   => 'Fir Resin, Cedarwood',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '15, 35, 56',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => true,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma hangat, amber, dan woody yang mewah dan elegan untuk momen istimewa.',
                'tagline'      => 'Amber, woody, warm spicy',
            ],
            [
                'name'         => 'Black XS',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Pria',
                'variant'      => 'Lemon, Marigold',
                'top_notes'    => 'Lemon, Marigold',
                'middle_notes' => 'Praline, Cinnamon, Cardamom',
                'base_notes'   => 'Patchouli, Black Amber, Ebony',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '15, 35, 57',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma sweet spicy dan woody dengan karakter maskulin modern.',
                'tagline'      => 'Sweet spicy, woody',
            ],
            [
                'name'         => 'Bvlgari Extreme',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Pria',
                'variant'      => 'Tea, Grapefruit, Bergamot',
                'top_notes'    => 'Tea, Grapefruit, Bergamot',
                'middle_notes' => 'Cardamom, Pepper, Rosewood',
                'base_notes'   => 'Musk, Cedar, Amber, Iris',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '15, 35, 58',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma bergamot dan tea yang segar dengan sentuhan kayu dan amber.',
                'tagline'      => 'Green tea, citrus, fresh spicy',
            ],
            [
                'name'         => 'Bvlgari Omnia Amethyste',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Wanita',
                'variant'      => 'Pink Grapefruit, Green Notes',
                'top_notes'    => 'Pink Grapefruit, Green Notes',
                'middle_notes' => 'Iris, Bulgarian Rose',
                'base_notes'   => 'Heliotrope, Woody Notes',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma floral irish dan green yang lembut, ringan, dan elegan.',
                'tagline'      => 'Floral, powdery, elegant',
            ],
            [
                'name'         => 'CH Good Girl',
                'type'         => 'Eau de Parfum',
                'gender'       => 'Wanita',
                'variant'      => 'Almond, Coffee, Bergamot',
                'top_notes'    => 'Almond, Coffee, Bergamot',
                'middle_notes' => 'Tuberose, Jasmine Sambac',
                'base_notes'   => 'Tonka Bean, Cacao, Vanilla',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma manis dan floral dengan sentuhan coffee dan vanilla yang elegan.',
                'tagline'      => 'Sweet floral, gourmand',
            ],
            [
                'name'         => 'Chanel Coco Mademoiselle',
                'type'         => 'Eau de Parfum',
                'gender'       => 'Wanita',
                'variant'      => 'Orange, Mandarin, Bergamot',
                'top_notes'    => 'Orange, Mandarin, Bergamot',
                'middle_notes' => 'Turkish Rose, Jasmine',
                'base_notes'   => 'Patchouli, White Musk, Vanilla',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma citrus floral yang elegan dengan sentuhan vanilla dan patchouli.',
                'tagline'      => 'Citrus, patchouli, sweet floral',
            ],
            [
                'name'         => 'Davidoff Cool Water',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Pria',
                'variant'      => 'Sea Water, Mint, Lavender',
                'top_notes'    => 'Sea Water, Mint, Lavender',
                'middle_notes' => 'Sandalwood, Jasmine, Neroli',
                'base_notes'   => 'Musk, Oakmoss, Tobacco',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma aquatic yang segar dan bersih dengan karakter maskulin yang ringan.',
                'tagline'      => 'Aquatic, fresh, aromatic',
            ],
            [
                'name'         => 'Dior Sauvage',
                'type'         => 'Eau de Toilette / Eau de Parfum',
                'gender'       => 'Pria',
                'variant'      => 'Bergamot, Pepper',
                'top_notes'    => 'Bergamot, Pepper',
                'middle_notes' => 'Sichuan Pepper, Lavender, Vetiver',
                'base_notes'   => 'Ambroxan, Cedar, Labdanum',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '60ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => true,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma fresh spicy dengan karakter modern, berani, dan maskulin.',
                'tagline'      => 'Fresh spicy, modern, bold',
            ],
            [
                'name'         => 'Dunhill Blue',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Pria',
                'variant'      => 'Litchi, Mandarin, Bergamot',
                'top_notes'    => 'Litchi, Mandarin, Bergamot',
                'middle_notes' => 'Sea Notes, Orange, Rosewood',
                'base_notes'   => 'Tonka Bean, Amber, Musk',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma citrus aquatic yang ringan, ideal untuk penggunaan sehari-hari.',
                'tagline'      => 'Citrus, aquatic, sweet amber',
            ],
            [
                'name'         => 'Escada Cherry in the Air',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Wanita',
                'variant'      => 'Sour Cherry, Raspberry',
                'top_notes'    => 'Sour Cherry, Raspberry',
                'middle_notes' => 'Marshmallow, Vanilla Orchid',
                'base_notes'   => 'Sandalwood, Oak, Musk',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma fruity manis dan playful, cocok untuk kesan ceria dan feminin.',
                'tagline'      => 'Fruity, sweet, playful',
            ],
            [
                'name'         => 'Escada Sexy Graffiti',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Wanita',
                'variant'      => 'Raspberry, Strawberry, Cassis',
                'top_notes'    => 'Raspberry, Strawberry, Cassis',
                'middle_notes' => 'Peony, Violet, Lily-of-the-Valley',
                'base_notes'   => 'Vanilla, Cashmere Wood, Musk',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma berry manis dengan sentuhan floral dan vanilla yang lembut.',
                'tagline'      => 'Fruity floral, sweet',
            ],
            [
                'name'         => 'Escada Sorbetto Rosso',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Wanita',
                'variant'      => 'Watermelon, Pear, Citrus',
                'top_notes'    => 'Watermelon, Pear, Citrus',
                'middle_notes' => 'Sea Salt, Water Notes, Rose',
                'base_notes'   => 'Amber, Musk, Praline',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma fruity aquatik yang segar dan playful untuk cuaca hangat.',
                'tagline'      => 'Fruity, aquatic, playful',
            ],
            [
                'name'         => 'Greed Aventus (Creed)',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Pria',
                'variant'      => 'Pineapple, Bergamot, Apple',
                'top_notes'    => 'Pineapple, Bergamot, Apple',
                'middle_notes' => 'Birch, Patchouli, Jasmine',
                'base_notes'   => 'Musk, Oakmoss, Ambergris',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma fruity smoky yang berkelas dan maskulin.',
                'tagline'      => 'Fruity, smoky, musk',
            ],
            [
                'name'         => 'Jaguar Blue',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Pria',
                'variant'      => 'Basil, Bergamot, Orange',
                'top_notes'    => 'Basil, Bergamot, Orange',
                'middle_notes' => 'Lavender, Lotus, Ginger',
                'base_notes'   => 'White Musk, Sandalwood',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma citrus aromatic yang segar dan energik untuk pria aktif.',
                'tagline'      => 'Aromatic, fresh, citrus',
            ],
            [
                'name'         => 'Miss Dior Blooming Bouquet',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Wanita',
                'variant'      => 'Sweet Pea, Bergamot',
                'top_notes'    => 'Sweet Pea, Bergamot',
                'middle_notes' => 'Damask Rose, Peony',
                'base_notes'   => 'White Musk',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma rose dan peony yang lembut, romantic, dan feminin.',
                'tagline'      => 'Rose, peony, soft musk',
            ],
            [
                'name'         => 'One Million Lucky',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Pria',
                'variant'      => 'Plum, Ozonic Notes, Grapefruit',
                'top_notes'    => 'Plum, Ozonic Notes, Grapefruit',
                'middle_notes' => 'Hazelnut, Honey, Cedar',
                'base_notes'   => 'Amberwood, Patchouli, Oakmoss',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma manis dan gourmand yang modern dengan sentuhan kacang dan kayu.',
                'tagline'      => 'Woody, sweet, gourmand',
            ],
            [
                'name'         => 'Polo Sport',
                'type'         => 'Eau de Toilette',
                'gender'       => 'Pria',
                'variant'      => 'Mint, Aldehydes, Lavender',
                'top_notes'    => 'Mint, Aldehydes, Lavender',
                'middle_notes' => 'Seagrass, Ginger, Jasmine',
                'base_notes'   => 'Sandalwood, Musk, Cedar',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma sportif, green, dan fresh yang cocok untuk aktivitas outdoor dan sehari-hari.',
                'tagline'      => 'Aromatic, green, fresh spicy',
            ],
            [
                'name'         => 'Vanilla Bodies',
                'type'         => 'Body Mist',
                'gender'       => 'Wanita',
                'variant'      => 'Whipped Cream, Sugar',
                'top_notes'    => 'Whipped Cream, Sugar',
                'middle_notes' => 'Vanilla Orchid, Coconut',
                'base_notes'   => 'Pure Vanilla, Cashmere Wood',
                'packaging'    => 'Botol Spray',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma vanilla creamy dan manis yang cocok untuk suasana santai.',
                'tagline'      => 'Sweet vanilla, creamy, gourmand',
            ],
            [
                'name'         => 'Vanilla Ice Pink Chiffon',
                'type'         => 'Body Mist',
                'gender'       => 'Wanita',
                'variant'      => 'Wild Berries, Pear, Peach',
                'top_notes'    => 'Wild Berries, Pear, Peach',
                'middle_notes' => 'Apple Blossom, Tiare Flower',
                'base_notes'   => 'Vanilla, Coconut, Sandalwood',
                'packaging'    => 'Botol Spray',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma creamy fruity lembut yang manis, cocok untuk pemakaian sehari-hari.',
                'tagline'      => 'Sweet vanilla, soft floral',
            ],
            [
                'name'         => 'Versace Eros',
                'type'         => 'Eau de Toilette / Eau de Parfum',
                'gender'       => 'Pria',
                'variant'      => 'Mint, Green Apple, Lemon',
                'top_notes'    => 'Mint, Green Apple, Lemon',
                'middle_notes' => 'Tonka Bean, Ambroxan, Geranium',
                'base_notes'   => 'Vanilla, Cedar, Vetiver',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => true,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma vanila mint yang kuat, modern, dan sangat cocok untuk malam hari.',
                'tagline'      => 'Vanilla, mint, woody',
            ],
            [
                'name'         => 'VS Amber Romance',
                'type'         => 'Body Mist',
                'gender'       => 'Wanita',
                'variant'      => 'Black Cherry, Custard',
                'top_notes'    => 'Black Cherry, Custard',
                'middle_notes' => 'Amber, Sugar, Sweet Notes',
                'base_notes'   => 'Vanilla, Sandalwood',
                'packaging'    => 'Botol Spray',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma vanilla manis dan amber yang hangat, cocok untuk gaya feminin dan manis.',
                'tagline'      => 'Amber, sweet, vanilla',
            ],
            [
                'name'         => 'VS Bombshell',
                'type'         => 'Eau de Parfum / Mist',
                'gender'       => 'Wanita',
                'variant'      => 'Passionfruit, Grapefruit, Pineapple',
                'top_notes'    => 'Passionfruit, Grapefruit, Pineapple',
                'middle_notes' => 'Peony, Vanilla Orchid',
                'base_notes'   => 'Musk, Woody Notes, Oakmoss',
                'packaging'    => 'Botol Spray',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma fruity floral dan sensual yang cocok untuk momen glamor.',
                'tagline'      => 'Fruity, fresh peony',
            ],
            [
                'name'         => 'VS So Sexy',
                'type'         => 'Eau de Parfum / Mist',
                'gender'       => 'Wanita',
                'variant'      => 'Bergamot, Apple, Passion Fruit',
                'top_notes'    => 'Bergamot, Apple, Passion Fruit',
                'middle_notes' => 'Lotus, Freesia, Rose',
                'base_notes'   => 'Vanilla, Sandalwood, Musk',
                'packaging'    => 'Botol Spray',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma fruity floral dengan sentuhan vanilla dan musk seksi.',
                'tagline'      => 'Fruity floral, sweet vanilla',
            ],
            [
                'name'         => 'White Musk (The Body Shop)',
                'type'         => 'Eau de Toilette / Eau de Parfum',
                'gender'       => 'Unisex',
                'variant'      => 'Musk, Lily, Ylang-Ylang',
                'top_notes'    => 'Musk, Lily, Ylang-Ylang',
                'middle_notes' => 'Musk, Lily, Rose, Jasmine',
                'base_notes'   => 'Musk, Oakmoss, Amber',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => true,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma musk white yang lembut, bersih, dan powdery cocok untuk semua gender.',
                'tagline'      => 'White musk, powdery, floral',
            ],
            [
                'name'         => 'YSL Black Opium',
                'type'         => 'Eau de Parfum',
                'gender'       => 'Wanita',
                'variant'      => 'Pear, Pink Pepper, Orange',
                'top_notes'    => 'Pear, Pink Pepper, Orange',
                'middle_notes' => 'Coffee, Jasmine, Almond',
                'base_notes'   => 'Vanilla, Patchouli, Cedar',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => true,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma kopi, vanilla, dan floral yang seksi dan modern untuk malam hari.',
                'tagline'      => 'Coffee, vanilla, floral',
            ],
            [
                'name'         => 'YSL Libre Women',
                'type'         => 'Eau de Parfum',
                'gender'       => 'Wanita',
                'variant'      => 'Lavender, Mandarin, Petitgrain',
                'top_notes'    => 'Lavender, Mandarin, Petitgrain',
                'middle_notes' => 'Lavender, Orange Blossom',
                'base_notes'   => 'Madagascar Vanilla, Musk',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma lavender floral yang elegan dengan sentuhan vanilla yang hangat.',
                'tagline'      => 'Lavender, orange blossom, vanilla',
            ],
            [
                'name'         => 'Zahrat Hawaii (Al-Rehab)',
                'type'         => 'Roll-On Oil',
                'gender'       => 'Unisex',
                'variant'      => 'Tropical Fruits, Pineapple',
                'top_notes'    => 'Tropical Fruits, Pineapple',
                'middle_notes' => 'Hibiscus, Citrus',
                'base_notes'   => 'Caramel, White Musk',
                'packaging'    => 'Roll-On',
                'size'         => '10ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma tropikal manis dengan sentuhan coconut dan floral yang cocok untuk suasana santai.',
                'tagline'      => 'Tropical, coconut, sweet floral',
            ],
            [
                'name'         => 'Zara Orchid',
                'type'         => 'Eau de Parfum',
                'gender'       => 'Wanita',
                'variant'      => 'Bergamot, Orchid, Rose, Lily-of-the-Valley',
                'top_notes'    => 'Bergamot',
                'middle_notes' => 'Orchid, Rose, Lily-of-the-Valley',
                'base_notes'   => 'Vanilla, Amber, Wood Notes',
                'packaging'    => 'Botol Spray Kaca',
                'size'         => '50ml',
                'price'        => 20000,
                'stock'        => 100,
                'best_seller'  => false,
                'image'        => 'assets/images/refill.webp',
                'description'  => 'Aroma floral vanila yang elegan dan ringan untuk penggunaan sehari-hari.',
                'tagline'      => 'Floral, citrus, vanilla',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
